# Generated by Django 5.1.1 on 2024-10-05 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('numero_edicion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('valoracion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycollection.comic')),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_adquisicion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('que me faltan', 'que me faltan'), ('disponibles para canje', 'disponibles para canje'), ('en la biblioteca', 'en la biblioteca'), ('Variant Cover', 'Variant Cover')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycollection.comic')),
            ],
        ),
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True)),
                ('estado_intercambio', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('comic_deseado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_recibidas', to='mycollection.comic')),
                ('comic_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_enviadas', to='mycollection.comic')),
                ('usuario_desea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
