# Generated by Django 5.1.1 on 2024-10-02 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleccion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='coleccion',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='estado',
            field=models.CharField(choices=[('que me faltan', 'que me faltan'), ('disponibles para canje', 'disponibles para canje'), ('en la biblioteca', 'en la biblioteca'), ('Variant Cover', 'Variant Cover')], max_length=50),
        ),
    ]
