# Generated by Django 5.1.1 on 2024-10-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollection', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
    ]
