# Generated by Django 5.1.1 on 2024-10-06 22:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycollection', '0003_comic_portada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='avatar',
            new_name='User_avatar',
        ),
    ]
